name: FuXiClimatePrediction
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy=1.26.4
  - zarr
  - pandas
  - jupyter
  - tqdm
  - python-dotenv
  - wandb
  - matplotlib
  - cartopy
  - xarray
  - ipympl
  - lightning
  - cdsapi
  - netcdf4
  - scipy
  - pydantic
  - pydantic-settings
